"""
All target venues extracted from client Excel files.
Each venue has a name, address, city, state, and optional known event source URLs.
"""

VENUES = [
    # ── WASHINGTON DC ─────────────────────────────────────────────────────────
    {
        "city_group": "Washington DC",
        "name": "DC Convention Center",
        "address": "801 Mt Vernon Pl NW, Washington, DC 20001",
        "city": "Washington",
        "state": "DC",
        "search_name": "Walter E Washington Convention Center DC",
        "source_urls": [],
    },
    {
        "city_group": "Washington DC",
        "name": "Marriott Marquis",
        "address": "901 Massachusetts Ave NW, Washington, DC 20001",
        "city": "Washington",
        "state": "DC",
        "search_name": "Marriott Marquis Washington DC",
        "source_urls": [],
    },
    {
        "city_group": "Washington DC",
        "name": "Hilton Washington DC Capitol Hill",
        "address": "525 New Jersey Ave NW, Washington, DC 20001",
        "city": "Washington",
        "state": "DC",
        "search_name": "Hilton Washington DC Capitol Hill",
        "source_urls": [],
    },
    {
        "city_group": "Washington DC",
        "name": "Renaissance Washington DC",
        "address": "999 9th St NW, Washington, DC 20001",
        "city": "Washington",
        "state": "DC",
        "search_name": "Renaissance Hotel Washington DC",
        "source_urls": [],
    },
    {
        "city_group": "Washington DC",
        "name": "Grand Hyatt Washington",
        "address": "1000 H St NW, Washington, DC 20001",
        "city": "Washington",
        "state": "DC",
        "search_name": "Grand Hyatt Washington DC",
        "source_urls": [],
    },
    {
        "city_group": "Washington DC",
        "name": "Omni Shoreham Hotel",
        "address": "2500 Calvert St NW, Washington, DC 20008",
        "city": "Washington",
        "state": "DC",
        "search_name": "Omni Shoreham Hotel Washington DC",
        "source_urls": [],
    },
    {
        "city_group": "Washington DC",
        "name": "JW Marriott Washington DC",
        "address": "1331 Pennsylvania Ave NW, Washington, DC 20004",
        "city": "Washington",
        "state": "DC",
        "search_name": "JW Marriott Washington DC",
        "source_urls": [],
    },
    # ── NATIONAL HARBOR / GAYLORD ─────────────────────────────────────────────
    {
        "city_group": "National Harbor MD",
        "name": "Gaylord National Harbor",
        "address": "201 Waterfront Street, National Harbor, MD 20745",
        "city": "National Harbor",
        "state": "MD",
        "search_name": "Gaylord National Harbor",
        "source_urls": [
            "https://www.marriott.com/en-us/hotels/wasge-gaylord-national-resort-and-convention-center/events/",
        ],
    },
    {
        "city_group": "National Harbor MD",
        "name": "Harborside Hotel National Harbor",
        "address": "6400 Oxon Hill Rd, National Harbor, MD 20745",
        "city": "National Harbor",
        "state": "MD",
        "search_name": "Harborside Hotel National Harbor MD",
        "source_urls": [],
    },
    {
        "city_group": "National Harbor MD",
        "name": "MGM National Harbor",
        "address": "101 MGM National Avenue, Oxon Hill, National Harbor, MD 20745",
        "city": "National Harbor",
        "state": "MD",
        "search_name": "MGM National Harbor hotel events",
        "source_urls": [],
    },
    # ── BETHESDA MD ───────────────────────────────────────────────────────────
    {
        "city_group": "Bethesda MD",
        "name": "Bethesda North Marriott Hotel & Conference Center",
        "address": "5701 Marinelli Road, North Bethesda, MD 20852",
        "city": "Bethesda",
        "state": "MD",
        "search_name": "Bethesda North Marriott Conference Center MD",
        "source_urls": [],
    },
    {
        "city_group": "Bethesda MD",
        "name": "Hyatt Regency Bethesda",
        "address": "7400 Wisconsin Avenue, Bethesda, MD 20814",
        "city": "Bethesda",
        "state": "MD",
        "search_name": "Hyatt Regency Bethesda MD",
        "source_urls": [],
    },
    {
        "city_group": "Bethesda MD",
        "name": "The Bethesdan Hotel",
        "address": "8120 Wisconsin Ave, Bethesda, MD 20814",
        "city": "Bethesda",
        "state": "MD",
        "search_name": "Bethesdan Hotel Bethesda MD",
        "source_urls": [],
    },
    # ── BALTIMORE MD ──────────────────────────────────────────────────────────
    {
        "city_group": "Baltimore MD",
        "name": "Baltimore Convention Center",
        "address": "1 W Pratt St, Baltimore, MD 21201",
        "city": "Baltimore",
        "state": "MD",
        "search_name": "Baltimore Convention Center",
        "source_urls": [
            "https://www.bccvb.com/events/",
        ],
    },
    {
        "city_group": "Baltimore MD",
        "name": "Hilton Baltimore Inner Harbor",
        "address": "401 W Pratt St, Baltimore, MD 21201",
        "city": "Baltimore",
        "state": "MD",
        "search_name": "Hilton Baltimore Inner Harbor hotel",
        "source_urls": [],
    },
    {
        "city_group": "Baltimore MD",
        "name": "Marriott Inner Harbor at Camden Yards",
        "address": "110 S Eutaw St, Baltimore, MD 21201",
        "city": "Baltimore",
        "state": "MD",
        "search_name": "Marriott Inner Harbor Camden Yards Baltimore",
        "source_urls": [],
    },
    {
        "city_group": "Baltimore MD",
        "name": "Four Seasons Baltimore",
        "address": "200 International Dr, Baltimore, MD 21202",
        "city": "Baltimore",
        "state": "MD",
        "search_name": "Four Seasons Hotel Baltimore",
        "source_urls": [],
    },
    {
        "city_group": "Baltimore MD",
        "name": "Embassy Suites Baltimore Inner Harbor",
        "address": "222 St Paul Pl, Baltimore, MD 21202",
        "city": "Baltimore",
        "state": "MD",
        "search_name": "Embassy Suites Baltimore Inner Harbor",
        "source_urls": [],
    },
    {
        "city_group": "Baltimore MD",
        "name": "Hyatt Regency Baltimore Inner Harbor",
        "address": "300 Light St, Baltimore, MD 21202",
        "city": "Baltimore",
        "state": "MD",
        "search_name": "Hyatt Regency Baltimore Inner Harbor",
        "source_urls": [],
    },
    {
        "city_group": "Baltimore MD",
        "name": "Baltimore Marriott Waterfront",
        "address": "700 Aliceanna St, Baltimore, MD 21202",
        "city": "Baltimore",
        "state": "MD",
        "search_name": "Baltimore Marriott Waterfront hotel",
        "source_urls": [],
    },
    {
        "city_group": "Baltimore MD",
        "name": "Renaissance Baltimore Harborplace Hotel",
        "address": "202 E Pratt St, Baltimore, MD 21202",
        "city": "Baltimore",
        "state": "MD",
        "search_name": "Renaissance Baltimore Harborplace Hotel",
        "source_urls": [],
    },
    {
        "city_group": "Baltimore MD",
        "name": "Courtyard Baltimore Downtown Inner Harbor",
        "address": "1000 Aliceanna St, Baltimore, MD 21202",
        "city": "Baltimore",
        "state": "MD",
        "search_name": "Courtyard Marriott Baltimore Inner Harbor",
        "source_urls": [],
    },
    {
        "city_group": "Baltimore MD",
        "name": "Hilton Garden Inn Baltimore Inner Harbor",
        "address": "625 S President St, Baltimore, MD 21202",
        "city": "Baltimore",
        "state": "MD",
        "search_name": "Hilton Garden Inn Baltimore Inner Harbor",
        "source_urls": [],
    },
    {
        "city_group": "Baltimore MD",
        "name": "Hotel Indigo Baltimore Downtown",
        "address": "24 W Franklin St, Baltimore, MD 21201",
        "city": "Baltimore",
        "state": "MD",
        "search_name": "Hotel Indigo Baltimore Downtown",
        "source_urls": [],
    },
    {
        "city_group": "Baltimore MD",
        "name": "Lord Baltimore Hotel",
        "address": "20 W Baltimore St, Baltimore, MD 21201",
        "city": "Baltimore",
        "state": "MD",
        "search_name": "Lord Baltimore Hotel events",
        "source_urls": [],
    },
    {
        "city_group": "Baltimore MD",
        "name": "Hampton Inn Baltimore Downtown Convention Center",
        "address": "550 Washington Blvd, Baltimore, MD 21201",
        "city": "Baltimore",
        "state": "MD",
        "search_name": "Hampton Inn Baltimore Downtown Convention Center",
        "source_urls": [],
    },
    # ── PHILADELPHIA PA ───────────────────────────────────────────────────────
    {
        "city_group": "Philadelphia PA",
        "name": "Pennsylvania Convention Center",
        "address": "1101 Arch St, Philadelphia, PA 19107",
        "city": "Philadelphia",
        "state": "PA",
        "search_name": "Pennsylvania Convention Center Philadelphia",
        "source_urls": [
            "https://www.paconvention.com/events/",
            "https://www.visitphilly.com/meeting-planners/upcoming-meetings-and-conventions/",
        ],
    },
    {
        "city_group": "Philadelphia PA",
        "name": "Philadelphia Marriott Downtown",
        "address": "1201 Market St, Philadelphia, PA 19107",
        "city": "Philadelphia",
        "state": "PA",
        "search_name": "Philadelphia Marriott Downtown hotel",
        "source_urls": [],
    },
    {
        "city_group": "Philadelphia PA",
        "name": "Loews Philadelphia Hotel",
        "address": "1200 Market St, Philadelphia, PA 19107",
        "city": "Philadelphia",
        "state": "PA",
        "search_name": "Loews Philadelphia Hotel events",
        "source_urls": [],
    },
    {
        "city_group": "Philadelphia PA",
        "name": "Element Philadelphia",
        "address": "1441 Chestnut St, Philadelphia, PA 19102",
        "city": "Philadelphia",
        "state": "PA",
        "search_name": "Element Hotel Philadelphia events",
        "source_urls": [],
    },
    {
        "city_group": "Philadelphia PA",
        "name": "Hyatt Centric Center City Philadelphia",
        "address": "1620 Chancellor St, Philadelphia, PA 19103",
        "city": "Philadelphia",
        "state": "PA",
        "search_name": "Hyatt Centric Center City Philadelphia",
        "source_urls": [],
    },
    {
        "city_group": "Philadelphia PA",
        "name": "Sheraton Philadelphia Downtown",
        "address": "201 N 17th St, Philadelphia, PA 19103",
        "city": "Philadelphia",
        "state": "PA",
        "search_name": "Sheraton Philadelphia Downtown Hotel",
        "source_urls": [],
    },
    {
        "city_group": "Philadelphia PA",
        "name": "W Philadelphia",
        "address": "1439 Chestnut St, Philadelphia, PA 19102",
        "city": "Philadelphia",
        "state": "PA",
        "search_name": "W Hotel Philadelphia events",
        "source_urls": [],
    },
    {
        "city_group": "Philadelphia PA",
        "name": "The Bellevue Hotel Philadelphia",
        "address": "200 S Broad St, Philadelphia, PA 19102",
        "city": "Philadelphia",
        "state": "PA",
        "search_name": "Bellevue Hotel Philadelphia events",
        "source_urls": [],
    },
    {
        "city_group": "Philadelphia PA",
        "name": "Circa Centre Philadelphia",
        "address": "2005 Market St, Philadelphia, PA 19103",
        "city": "Philadelphia",
        "state": "PA",
        "search_name": "Circa Centre Philadelphia conference",
        "source_urls": [],
    },
    {
        "city_group": "Philadelphia PA",
        "name": "The Logan Hotel Philadelphia",
        "address": "1 Logan Sq, Philadelphia, PA 19103",
        "city": "Philadelphia",
        "state": "PA",
        "search_name": "Logan Hotel Philadelphia events",
        "source_urls": [],
    },
    {
        "city_group": "Philadelphia PA",
        "name": "Four Seasons Philadelphia",
        "address": "1 N 19th St, Philadelphia, PA 19103",
        "city": "Philadelphia",
        "state": "PA",
        "search_name": "Four Seasons Hotel Philadelphia",
        "source_urls": [],
    },
    {
        "city_group": "Philadelphia PA",
        "name": "Sofitel Philadelphia at Rittenhouse Square",
        "address": "120 S 17th St, Philadelphia, PA 19103",
        "city": "Philadelphia",
        "state": "PA",
        "search_name": "Sofitel Philadelphia Rittenhouse Square events",
        "source_urls": [],
    },
    {
        "city_group": "Philadelphia PA",
        "name": "The Ritz-Carlton Philadelphia",
        "address": "10 Avenue of the Arts, Philadelphia, PA 19102",
        "city": "Philadelphia",
        "state": "PA",
        "search_name": "Ritz-Carlton Philadelphia events conference",
        "source_urls": [],
    },
    {
        "city_group": "Philadelphia PA",
        "name": "The Union League of Philadelphia",
        "address": "140 S Broad St, Philadelphia, PA 19102",
        "city": "Philadelphia",
        "state": "PA",
        "search_name": "Union League Philadelphia events",
        "source_urls": [],
    },
    {
        "city_group": "Philadelphia PA",
        "name": "Sonesta Philadelphia Downtown Rittenhouse Square",
        "address": "1800 Market St, Philadelphia, PA 19103",
        "city": "Philadelphia",
        "state": "PA",
        "search_name": "Sonesta Philadelphia Downtown events",
        "source_urls": [],
    },
    {
        "city_group": "Philadelphia PA",
        "name": "Marriott Philadelphia Old City",
        "address": "One Dock St, Philadelphia, PA 19106",
        "city": "Philadelphia",
        "state": "PA",
        "search_name": "Marriott Philadelphia Old City hotel events",
        "source_urls": [],
    },
    {
        "city_group": "Philadelphia PA",
        "name": "Kimpton Palomar Philadelphia",
        "address": "117 S 17th St, Philadelphia, PA 19103",
        "city": "Philadelphia",
        "state": "PA",
        "search_name": "Kimpton Palomar Philadelphia events",
        "source_urls": [],
    },
    {
        "city_group": "Philadelphia PA",
        "name": "Kimpton Monaco Philadelphia",
        "address": "433 Chestnut St, Philadelphia, PA 19106",
        "city": "Philadelphia",
        "state": "PA",
        "search_name": "Kimpton Monaco Philadelphia events",
        "source_urls": [],
    },
    {
        "city_group": "Philadelphia PA",
        "name": "Live Casino & Hotel Philadelphia",
        "address": "900 Packer Ave, Philadelphia, PA 19148",
        "city": "Philadelphia",
        "state": "PA",
        "search_name": "Live Casino Hotel Philadelphia events",
        "source_urls": [],
    },
    {
        "city_group": "Philadelphia PA",
        "name": "Hilton Philadelphia Penn's Landing",
        "address": "201 S Columbus Blvd, Philadelphia, PA 19106",
        "city": "Philadelphia",
        "state": "PA",
        "search_name": "Hilton Philadelphia Penn's Landing events",
        "source_urls": [],
    },
    {
        "city_group": "Philadelphia PA",
        "name": "Airport Marriott Philadelphia",
        "address": "1 Arrivals Rd, Philadelphia, PA 19153",
        "city": "Philadelphia",
        "state": "PA",
        "search_name": "Philadelphia Airport Marriott events",
        "source_urls": [],
    },
    {
        "city_group": "Philadelphia PA",
        "name": "Valley Forge Casino Resort",
        "address": "1160 First Ave, King of Prussia, PA 19406",
        "city": "King of Prussia",
        "state": "PA",
        "search_name": "Valley Forge Casino Resort events conference",
        "source_urls": [],
    },
    {
        "city_group": "Philadelphia PA",
        "name": "Oaks Expo Center",
        "address": "100 Station Ave, Oaks, PA 19456",
        "city": "Oaks",
        "state": "PA",
        "search_name": "Oaks Expo Center Pennsylvania events",
        "source_urls": [],
    },
    {
        "city_group": "Philadelphia PA",
        "name": "Temple University Conference Services",
        "address": "1801 N Broad St, Philadelphia, PA 19122",
        "city": "Philadelphia",
        "state": "PA",
        "search_name": "Temple University conference events Philadelphia",
        "source_urls": [],
    },
    {
        "city_group": "Philadelphia PA",
        "name": "Warwick Hotel Philadelphia",
        "address": "1701 Locust St, Philadelphia, PA 19103",
        "city": "Philadelphia",
        "state": "PA",
        "search_name": "Warwick Hotel Philadelphia events",
        "source_urls": [],
    },
    {
        "city_group": "Philadelphia PA",
        "name": "Notary Hotel Philadelphia",
        "address": "21 N Juniper St, Philadelphia, PA 19107",
        "city": "Philadelphia",
        "state": "PA",
        "search_name": "Notary Hotel Philadelphia events",
        "source_urls": [],
    },
    # ── DELAWARE ──────────────────────────────────────────────────────────────
    {
        "city_group": "Delaware",
        "name": "Chase Center on the Riverfront",
        "address": "815 Justison St, Wilmington, DE 19801",
        "city": "Wilmington",
        "state": "DE",
        "search_name": "Chase Center Riverfront Wilmington Delaware events",
        "source_urls": [],
    },
    {
        "city_group": "Delaware",
        "name": "Hotel DuPont",
        "address": "42 West 11th St, Wilmington, DE 19801",
        "city": "Wilmington",
        "state": "DE",
        "search_name": "Hotel DuPont Wilmington Delaware events",
        "source_urls": [],
    },
    {
        "city_group": "Delaware",
        "name": "DoubleTree by Hilton Wilmington",
        "address": "4727 Concord Pike, Wilmington, DE 19803",
        "city": "Wilmington",
        "state": "DE",
        "search_name": "DoubleTree Hilton Wilmington Delaware events",
        "source_urls": [],
    },
    {
        "city_group": "Philadelphia PA",
        "name": "Holiday Inn Drexel Hill Philadelphia",
        "address": "1 West Avenue, Drexel Hill, PA 19026",
        "city": "Drexel Hill",
        "state": "PA",
        "search_name": "Holiday Inn Drexel Hill Philadelphia events",
        "source_urls": [],
    },
    {
        "city_group": "Philadelphia PA",
        "name": "Temple University Conference Center",
        "address": "1801 N Broad St, Philadelphia, PA 19122",
        "city": "Philadelphia",
        "state": "PA",
        "search_name": "Temple University conference center Philadelphia events",
        "source_urls": [],
    },
]

# ── KNOWN INDUSTRY SOURCES (exact list from client's "Event websites" tab in Philadelphia Excel) ──
INDUSTRY_SOURCES = [
    # From client's own list
    "https://allconferencealert.net/usa.php",
    "https://10times.com/united-states",
    "https://www.biztradeshows.com/united-states/",
    "https://www.eventsinamerica.com",
    "https://www.eventseye.com/fairs/c3_trade-shows-usa.html",
    "https://www.expodatabase.com/shows/country/united-states/",
    "https://tradeshowz.com/",
    "https://thetradeshowcalendar.com/ttn/index.php",
    "https://www.tradeshowhandbook.com/trade-show-directory.html",
    "https://tsnn.com/events",
    "https://conferencenext.com/conferences/washington-dc",
    "https://conferencenext.com/conferences/philadelphia",
    "https://conferencenext.com/conferences/baltimore",
    "https://internationalconferencealerts.com/",
    "https://www.iaee.com/events/",
    "https://www.jupiterevents.com",
    "https://conventionplanit.com",
    "https://www.blackmeetingsandtourism.com/events/",
    "https://www.experienceprincegeorges.com/meetings/destination-services/",
    "https://www.capitalregionusa.org/",
    # Additional reliable sources
    "https://www.pcma.org/events/",
    "https://www.mpi.org/events/",
    "https://www.asaecenter.org/programs-and-training/meetings-list",
    "https://www.meetingsnet.com/event-listings",
    "https://www.visitphilly.com/meeting-planners/upcoming-meetings-and-conventions/",
    "https://www.visitbaltimore.org/meetings/upcoming-events/",
    "https://washington.org/dc-meetings/meetings-conventions-dc",
]

# ── SEARCH TYPES (exact list from Research DC instructions doc) ───────────────
EVENT_TYPES = [
    # From the client's instructions document (exact terms)
    "Conference", "Tradeshow", "Meeting", "Expo", "Symposium",
    "Convention", "Summit", "Sales Meeting", "Financial Meeting",
    "Congress", "Consumer Show", "Association", "Webinar",
    "Clinical Meeting", "Show", "Training Summit", "Annual Meeting",
    "Forums", "Event", "Exposition", "Users Group", "Compliance",
    "Food Event", "Festival", "Wine Event",
    # Additional types for broader coverage
    "Trade Fair", "Gala", "Live Event", "Award Ceremony",
    "Networking Event", "Seminar", "Workshop", "Meetings",
]

# ── CITY-SPECIFIC EXTRA PHRASES (from "Addition search" tab in Philadelphia Excel) ──
# These are added ON TOP of the standard month+type+venue phrases
CITY_EXTRA_PHRASES = {
    "Philadelphia": [
        "{city} meeting listings",
        "{city} convention listings",
        "{city} trade show listings",
        "{city} business event listings",
        "{city} professional event calendar",
        "{city} expo listings",
        "{city} conference listings",
        "{city} industry event calendar",
        "{city} event venue listings",
        "{city} convention center events",
        "upcoming meetings in {city}",
        "upcoming annual meeting in {city}",
        "corporate meetings in {city}",
        "business meetings in {city}",
        "association meetings in {city}",
        "networking meetings in {city}",
    ],
    "Baltimore": [
        "{city} meeting listings",
        "{city} convention listings",
        "{city} conference listings",
        "{city} trade show listings",
        "upcoming meetings in {city}",
        "association meetings in {city}",
        "corporate events in {city}",
    ],
    "Washington": [
        "{city} DC meeting listings",
        "{city} DC convention listings",
        "{city} DC conference listings",
        "{city} DC trade show listings",
        "upcoming meetings in {city} DC",
        "association meetings {city} DC",
    ],
    "Wilmington": [
        "{city} Delaware meeting listings",
        "{city} Delaware conference listings",
        "upcoming events {city} Delaware",
    ],
    "National Harbor": [
        "National Harbor MD events",
        "National Harbor Maryland conference",
        "National Harbor Maryland tradeshow",
    ],
    "Bethesda": [
        "{city} Maryland meeting listings",
        "{city} MD conference listings",
        "upcoming meetings {city} Maryland",
    ],
}

# ── CONTACT TITLE FILTER ──────────────────────────────────────────────────────
TARGET_TITLES = [
    "CMP", "Event Manager", "Meeting Manager", "Conference Planner",
    "Registration Manager", "Lead Retrieval", "Director of Events",
    "Events Director", "Event Coordinator", "Conference Manager",
    "Meeting Planner", "Convention Manager", "Trade Show Manager",
    "Director of Meetings", "Events Manager", "Meeting Director",
    "Conference Director", "Convention Planner",
]
